when:
  - event: push
    branch: main

steps:
  - name: build
    image: paulhuggett/ubuntu-build
    commands:
      - mkdir build
      - cmake -S . -B build -G Ninja
      - ninja -C build
  - name: a-test-step
    image: paulhuggett/ubuntu-build
    commands:
      - echo "Testing One, Two..."
      - ./build/hello
  - name: upload
    image: paulhuggett/ktransfer:latest
    pull: true
    settings:
      token:
        from_secret: API_TOKEN
      drive_id: 641975
      method: put
      name: './build/hello'
  - name: One last thing
    image: paulhuggett/ubuntu-build
    commands:
      - echo "Done"

